### ISSUE TITLE
Module breaks OXID admin area because of removed function getInstance()

### ISSUE THREAD

**Issue by hkockerbeck** [leofonic/activate-reviews#1]
The Singleton method `getInstance()` has been deprecated since OXID v4.7.5, and has been removed since v4.9.0 (see [wiki.oxidforge.org](http://wiki.oxidforge.org/Downloads/4.9.0_5.2.0#Removed_deprecated_method_getInstance.28.29)). This module uses `oxLang::getInstance()` in `admin/activate_reviews_navigation.php` to show the number of new reviews on the main admin page. Because that function isn't available any more, this isn't working and most of the admin area isn't displayed. 

According to [this tutorial](http://wiki.oxidforge.org/Tutorials/bootstrap_process_refactored_in_4.7_5.0#Singletons_are_replaced_by_registry), calls to the Singletons should be replaced with calls to `oxRegistry::get`: `oxLang::getInstance()` -> `oxRegistry::get('oxLang')`.

**Comment by leofonic** [comment]
Sorry didn't notice, corrected it while making the 6.x version, thank you.
